[package]
name = "blendermanager"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
flate2 = "1.1.5"
reqwest = { version = "0.12.24", features = ["blocking", "json"] }
scraper = "0.24.0"
tar = "0.4.44"
xz2 = "0.1.7"
